
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 31 13:15:29 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 42;
  public static final int OP_RIGHT_SQUARE = 19;
  public static final int CONST = 20;
  public static final int OP_LESS_THAN = 38;
  public static final int OP_AND = 23;
  public static final int CONTINUE = 25;
  public static final int NUM_CONST = 40;
  public static final int FOR = 28;
  public static final int OP_EQUALS = 15;
  public static final int OP_DIV = 33;
  public static final int OP_LEFT_BRACE = 4;
  public static final int OP_DOT = 30;
  public static final int CLASS = 16;
  public static final int OP_LESS_EQUAL = 39;
  public static final int OP_MUL = 32;
  public static final int IF = 44;
  public static final int OP_MINUSMINUS = 14;
  public static final int OP_RIGHT_BRACE = 5;
  public static final int OP_MOD = 34;
  public static final int ABSTRACT = 17;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int OP_GREATER_THAN = 36;
  public static final int NEW = 27;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int OP_SEMICOLON = 6;
  public static final int OP_LEFT_SQUARE = 18;
  public static final int OP_OR = 22;
  public static final int IDENT = 43;
  public static final int BREAK = 24;
  public static final int OP_ASSIGN = 29;
  public static final int VOID = 3;
  public static final int OP_PLUSPLUS = 13;
  public static final int OP_GREATER_EQUAL = 37;
  public static final int OP_MINUS = 31;
  public static final int ELSE = 45;
  public static final int READ = 26;
  public static final int OP_NOT_EQUALS = 35;
  public static final int OP_COMMA = 9;
  public static final int EXTENDS = 21;
  public static final int OP_LEFT_PAREN = 7;
  public static final int BOOL_CONST = 41;
  public static final int OP_PLUS = 12;
  public static final int OP_RIGHT_PAREN = 8;
  public static final int PRINT = 10;
}

